### ISSUE TITLE
Installing Pyfda

### ISSUE THREAD

**Issue by WinMic** [chipmuenk/pyFDA#10]
Wanted to install the new version. Used the described command "python setup.py -install" form the mainpage. If you look in the setup help using "python setup.py --help", the install command is  "python setup.py install". Without the "-" which works perfectly fine :)

**Comment by chipmuenk** [comment]
Thanx @WinMic for spotting the bug (and welcome back!)  and thanx to @cfelton who was faster than me fixing it!
