### ISSUE TITLE
Possible to simulate performance of an IIR using single precision float? 

### ISSUE THREAD

**Issue by whoopsmith** [chipmuenk/pyFDA#101]
I have some IIR filters that are currently running with double precision math.  I'd like to move them to CMSIS DSP assisted f32() functions on a cortexM4 with an FPU but I'm worried what its going to do to the filter performance.  Is there a way to simulate this with pyFDA.  

I see the fixed point stuff but I don't see anything that looks like its a single precision float.

**Comment by chipmuenk** [comment]
You are right, single precision float isn't implemented yet. Your question is actually two questions :-)
- Coefficients need to be quantized, this part is implemented for various fixpoint formats but not for single precision floats. This is a good idea and could be easily implemented.
- Especially for IIR filters, the topology (direct form, second order sections, ...) and internal word length / data format can be even more important for the performance than coefficient format. This part  - arithmetic quantization - is much more difficult to implement, as the standard scipy routines like freqz() etc. can no longer be used. This feature is targeted for the next release.

**Comment by whoopsmith** [comment]
Thanks for the answer.
