### ISSUE TITLE
'async' is a keyword in Python >= 3.5

### ISSUE THREAD

**Issue by MachFour** [chipmuenk/pyFDA#137]
There's a minor syntax error that occurs when byte-compiling `fixpoint_widgets/filter_iir.py`, because the `ResetSignal` function from MyHDL has a keyword argument called 'async', which is a keyword in Python versions above 3.5.

I guess the developers of MyHDL haven't been using a recent version of Python, so until that gets updated, an easy workaround to get pyFDA to byte-compile properly is to just change the keyword arguments to positional arguments, i.e.
```#reset = ResetSignal(0, active=1, async=False)
reset = ResetSignal(0, 1, False)
```
Otherwise, thanks for making this really cool program!

**Comment by chipmuenk** [comment]
Thanx for your kind words and for your bug report! Unfortunately, I've been quite busy during the last months and haven't found the time to really merge and stabilize the HDL bits from the GSoC 2018 yet. I'll take care of that at the end of the year.

**Comment by chipmuenk** [comment]
I took a look into the issue: filter_iir.py is an outdated module that is no longer needed, unfortunately it is still imported and referenced in df1.py and df2.py. Commenting out all imports and references of / to filter_iir.py makes no difference to the functionality - I'll make a new release in the next few weeks once I have solved some test failures.

**Comment by chipmuenk** [comment]
fixed in current branch master
