### ISSUE TITLE
passing parameter for Kaiser Window

### ISSUE THREAD

**Issue by bhmercier** [chipmuenk/pyfda#155]
How to pass parameter (beta) for Kaiser windowing?
Without it, I get the error:
[filter_factory.py:234] ErrCode 99: Method 'LPmin' of class 'Firwin':
The 'kaiser' window needs one or more parameters -- pass a tuple.

**Comment by chipmuenk** [comment]
How are you trying to design the filter? Do you use pyFDA with the GUI or are you using the filter design routines in your own software?

When designing a filter in the GUI this error shouldn't happen - which is your pyfda version?

**Comment by bhmercier** [comment]
Hello,
I use pyfda in the GUI. My version is 0.1.5. All other windows are working, but the Kaiser one requires a parameter (I guess it is the beta value), and I don't know how to pass it.

**Comment by chipmuenk** [comment]
Hm, I'm sorry - I guess you found a bug in 0.1.5 that I must have fixed 
in the 0.2 branch at some point ... and yes, it's the beta value. I'll 
finally release version 0.2 next, please have some patience till then!

Am 18.10.19 um 19:34 schrieb bhmercier:

**Comment by bhmercier** [comment]
Christian, thanks for your prompt answer. I think you will easily correct this bug!
Cheers.
Bernard

**Comment by bhmercier** [comment]
Hi Christian,
In fact the same issue exists each time one ore parameter is needed, namely for the following windows:
- chebwin
- gaussian
- general gaussian
- kaiser
- slepian
BRegards,
Bernard

**Comment by chipmuenk** [comment]
Thanks once more for reporting, please try the new and shiny version 0.2.
