### ISSUE TITLE
Export coefficients in SOS format

### ISSUE THREAD

**Issue by gaosiy** [chipmuenk/pyfda#190]
As mention in the title, I can't find the way to export SOS params, can you help me?

**Comment by chipmuenk** [comment]
Unfortunately, this is not implemented yet. The scipy IIR filter designs return the coefficients in SOS format but I haven't found the time to display and export them. Are you interested in float or in fixpoint format? The latter is on my todo list as well but this is even further down the road ...

**Comment by gaosiy** [comment]
> Unfortunately, this is not implemented yet. The scipy IIR filter designs return the coefficients in SOS format but I haven't found the time to display and export them. Are you interested in float or in fixpoint format? The latter is on my todo list as well but this is even further down the road ...

Thanks for your reply and your very nice work! I have used the _iirdesign_ function to export SOS params, and then plot the response wave with matplotlib.

**Comment by chipmuenk** [comment]
moved to #226.
