### ISSUE TITLE
executable generation with pyinstaller

### ISSUE THREAD

**Issue by Matiu-f** [chipmuenk/pyfda#203]
I can't generate a working executable with pyinstaller on a windows10 machine. Could you please provide an executable? Thanks a lot for your work.

**Comment by chipmuenk** [comment]
Which error do you get? I'll provide a new executable for the next release (in ca. 2  ... 3 weeks), please use the executable for the last release in the meantime.

**Comment by Matiu-f** [comment]
Sorry, maybe is a very noob question, but I can't find any executable between the provided files. Am I missing something?
