### ISSUE TITLE
UI labels same color as background under MacOS

### ISSUE THREAD

**Issue by chipmuenk** [chipmuenk/pyfda#204]
I've seen this bug under MacOS only so far. It could be related to Qt bugs 73897 / 71020 which have been reported for macOS 10.14 with Dark Theme and Qt 5.12.

https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-73897 
https://bugreports.qt.io/browse/QTBUG-71020

Please confirm / disagree, I have no access to a MacOS computer.

**Comment by chipmuenk** [comment]
Could not be reproduced

**Comment by dsvf** [comment]
This is still an issue here. Mac OS Sonoma 14.6.1., latest pyfda.
A screenshot of pyfdax in regular/light mode:
<img width="1624" alt="grafik" src="https://github.com/user-attachments/assets/2f7f23a6-2d05-44df-97cc-89028e9c364a">

A screenshot of pyfdax when the system is in dark mode:
<img width="1624" alt="grafik" src="https://github.com/user-attachments/assets/88cb8883-df2a-48d5-93fe-02713bd4997f">

If you need testing for a fix, I'd be happy to do so, and use light theme while using pyfda in the meantime.

**Comment by chipmuenk** [comment]
Could you please check whether pyfda 0.9.1 has fixed the problem? You should get a dark mode by setting `THEME = 'dark' ` in your `pyfda.conf` file.

**Comment by dsvf** [comment]
Yes! Light mode is perfectly legible and dark mode is looking really good! Thank you for the fix!
