### ISSUE TITLE
Files tab missing

### ISSUE THREAD

**Issue by CybEng** [chipmuenk/pyfda#205]
The "Files" tab is missing on the left part of the program window.
Tabs "Specs", "b,a", "P/Z", "Info" and "HDL" are all there and appear to work OK.

OS : Ubuntu 20.04
Python : 3.8.10
pyFDA installation method : pip3 install pyfda --user

**Comment by chipmuenk** [comment]
Thanks for opening the issue but I have removed the "Files" tab a few versions ago. You can save the complete filter under "Specs" or coefficients and P/Z under the corresponding tabs. If you have a tab "HDL" you're using a very old version; it has bee renamed to "Fixpoint". What is  it that you want do save or load?
