### ISSUE TITLE
Entering complex coefficients crashes pyfda

### ISSUE THREAD

**Issue by chipmuenk** [chipmuenk/pyfda#212]
This can be reproduced by selecting a FIR filter in the coefficient tab, clearing the coefficients and entering the coefficients '1' and '1j' and saving.

```
d:\daten\design\python\git\pyfda\pyfda\input_widgets\input_coeffs.py:254: ComplexWarning: Casting complex values to real discards the imaginary part
  self.parent.ba[0] = self.parent.ba[0].astype(complex)
d:\daten\design\python\git\pyfda\pyfda\input_widgets\input_coeffs.py:255: ComplexWarning: Casting complex values to real discards the imaginary part
  self.parent.ba[1] = self.parent.ba[1].astype(complex)
Traceback (most recent call last):
  File "d:\daten\design\python\git\pyfda\pyfda\input_widgets\input_coeffs.py", line 256, in setModelData
    self.parent.ba[index.column()][index.row()] = data  # store in self.ba
TypeError: can't convert complex to float
```

Creating complex coefficients by deleting a pole or zero in the P/Z editor, does not cause a crash. Editing the complex coefficients created this way also works without problems.

**Comment by jeanibarz** [comment]
I'm looking at this problem. As of today, I've been able to reproduce the bug into the branch "file_io", but not on branch "master".

**Comment by jeanibarz** [comment]
When a complex pole/zero was entered, the array `ba` was converted into complex type if necessary, but not the `ba_q` array. Trying to assign the complex value to float type array `ba_q` was causing the crash, hence I added a line to convert `ba_q` into complex type before assignment, similarly to what was done with the `ba` array.
