### ISSUE TITLE
Biquad Filters

### ISSUE THREAD

**Issue by PAk-CatchFire** [chipmuenk/pyfda#213]
I wonder if it is possible with this marvellous tool to generate Biquad IIR filters. 

Some DSPs and MCUs, do have biquad libraries as a very efficient implementation form, so expanding this tool could be really useful for this purpose.

Thank you. 
Best Regards

**Comment by chipmuenk** [comment]
That's indeed on my todo list for quite a while now. Currently, I'm working on some file I/O issues and I'm planning to add an export option for coefficients in second-order sections format (i.e. biquads). What would be most useful to you - exporting

- SOS coefficients as floats
- SOS coefficients as integers (this probably requires an additional gain factor per section to overcome scaling issues)
- header files with the coefficients in C format (example needed)
- C files with the actual filter topology (example needed, maybe even as a template as I'd like to generate ready to use filters from templates)

Contributing examples and / or templates would be most helpful!

**Comment by PAk-CatchFire** [comment]
In case it helps with python, a couple of links from ARM:

https://developer.arm.com/documentation/102463/0100

and a PDF:
https://developer.arm.com/-/media/Arm%20Developer%20Community/PDF/How%20to%20use%20the%20Python%20wrapper%20for%20CMSIS-DSP%20with%20biquads%20as%20an%20example.pdf?revision=9a6360f1-e2eb-4d18-83d2-3825c9486dc1

**Comment by chipmuenk** [comment]
Thanks for all the links! If I understand you correctly, you would like to get the biquad coefficients in the format
` {b10, b11, b12, a11, a12, b20, b21, b22, a21, a22, ...}` as floats as described in https://www.keil.com/pack/doc/CMSIS/DSP/html/group__BiquadCascadeDF2T.html ? That should be possible without a big effort.

**Comment by PAk-CatchFire** [comment]
Yes, that could be a fantastic direct first step. 

The idea later could be to use the CMSIS library wrapper for test the embedded library with your graphic tool - so powerful and handy!! 

Again, congratulations on your work on this awesome tool. I will use it with some of our internship students for filter designing (I try to avoid MATLAB as much as possible to provide them opensource engineering tools).

**Comment by PAk-CatchFire** [comment]
Hello @chipmmuenk, do you plan on a new release any time soon?

Best Regards

**Comment by chipmuenk** [comment]
Sorry for leaving you waiting for so long - I'm justing implementing some Github Actions at the moment to automate building and releasing to PyPI and then there will be a full new release during the next week. The main branch already contains the CMSIS export, somewhat hidden in the CSV options and is fully functional. In my opinion a new tab / subwidget is required in the future to allow a.o. selecting the order of second order sections and setting fixpoint options.

**Comment by PAk-CatchFire** [comment]
Thank you.
I am converting Pyfda in my preferred tool for filter designing (so fast and powerful!!)
However, I don't see how to get the CMSIS format export in the CSV.

What I see is the same coefficients as the  npy format when I import it in python:
![image](https://user-images.githubusercontent.com/4245130/206916819-e4521cb6-4fd8-4456-b7a5-0d455d1446a6.png)

Maybe I am missing something?

On the other hand, do you have a time frame for implementing in the GUI the Biquad Cascade IIR Filters Using a Direct Form II Transposed format? 
Like in Matlab:
https://es.mathworks.com/help/dsp/ref/dsp.biquadfilter-system-object.html

I am seeing that many embedded applications are porting into this format because they are a quite efficient implementation.

Regards

**Comment by chipmuenk** [comment]
I've started working on fixpoint filters again. The export option for CMSIS SOS format is implemented for quite a while now but it is hidden somewhat: Open CSV option (the little cog) in the b,a tab and select CMSIS SOS format.

Does this export format work for you?

Regards

**Comment by chipmuenk** [comment]
Since v0.9.0b1, coefficients can be saved directly in CMSIS SOS format via "save coefficients".
