### ISSUE TITLE
 upload-release-asset in build_flatpak.yml

### ISSUE THREAD

**Issue by Murmele** [chipmuenk/pyfda#229]
Currently the releases are done in build_pyinstaller.yml. Flatpak is build in build_flatpak.yml when I use also upload-release-assert. Do I overwrite then the already published files?

By the way: On flathub the newest version is published :)

**Comment by chipmuenk** [comment]
Sorry for the very late response but I hadn't managed to setup the build and release process for a "latest" release till today. Yes, `build_flatpak.yml` overwrites my latest release created by `build_pystaller_latest.yml`, using the marketplace action `pyTooling/Actions/releaser@main`. This workflow supports an 'rm = false' option, pushing assets to 'latest' release without deleting everything.

The flatpak building process takes much longer than the pyinstaller build processes so I started `build_pystaller_latest.yml` manually which works. Does `build_flatpak.yml` have a similar option?

BTW: I updated the standard actions to newer releases to remove deprecation warnings but some warnings still remain. Perhaps you could take a look at this?

**Comment by chipmuenk** [comment]
I've updated the github actions, it should work now, but please check on the flathub side.
