### ISSUE TITLE
Crash when trying to open inset plot in H(f)

### ISSUE THREAD

**Issue by sa425316543** [chipmuenk/pyfda#234]
Python version: 3.9.13
pyfda version 0.7.1 installed from PyPI.

[   INFO] [pyfda.plot_widgets.plot_impz:654] [    0 ms]: Calculated transient fixpoint response
[   INFO] [pyfda.plot_widgets.plot_impz:660] [171.9 ms]: Plotted transient fixpoint response
Traceback (most recent call last):
  File "C:\Projects\Misc\venv\lib\site-packages\pyfda\plot_widgets\plot_hf.py", line 489, in draw_inset
    self.ax_i.patches.append(rect)
AttributeError: 'ArtistList' object has no attribute 'append'

**Comment by chipmuenk** [comment]
The error occurs when trying to use an inset plot in the H(f) tab (draw_inset() method), no need to start a fixpoint simulation. I can reproduce the error with python 3.10.10 and matplotlib 3.7.1, everything runs smooth with Python 3.9.16 and Matplotlib 3.6.0. 

Could you be so kind to check your Matplotlib version?

**Comment by chipmuenk** [comment]
From the Matplotlib reference for `matplotlib.axes.Axes.ArtistList()`:

> The type-specific children sublists were made immutable in Matplotlib 3.7. In the future these artist lists may be replaced by tuples. Use as if this is a tuple already.
