### ISSUE TITLE
fixpoint coefficients crash pyfda

### ISSUE THREAD

**Issue by ksrp1984** [chipmuenk/pyfda#238]
Good day! I have this problem. Version: 0.8.2 (Windows). When I click on the save icon the program closes.
Terminal message: ValueError: "setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part."
If you save Float then there is no problem. The problem is only when saving Fixpoint coefficients.
[hilbert_pyfdax.zip](https://github.com/chipmuenk/pyfda/files/12586595/hilbert_pyfdax.zip)

**Comment by chipmuenk** [comment]
Thanks for reporting, I believe the error is related to #230, I'll take a look at it tomorrow!

**Comment by chipmuenk** [comment]
Fixed in latest, please test! Version 0.8.3 will be released today or tomorrow.

**Comment by ksrp1984** [comment]
Version 0.8.3.  The program doesn't crash when I click "Save" with fixed point coefficients. But the coefficients are not saved. Nothing happens
