### ISSUE TITLE
FR: Settings for Plot spacing/Interpolation

### ISSUE THREAD

**Issue by stellarpower** [chipmuenk/pyfda#259]
Hi,

Maybe this already exists, but I've not managed to find it.

I'm often working with pretty narrow and low-frequency filters. When the repsonse curves are plotted, the lines can be pretty coarse, making it a bit harder to get a good idea of the shape when comparing different filters (and also checking that I've converted co-efficients between different formats properly. Sometimes there are numerical precision issues, but it might also just be the plotting settings):

![image](https://github.com/user-attachments/assets/e228fa86-659c-4d29-84ef-70d09a65d1a4)

(This is on version 0.9.0b1)

I'd like to be able to edit a setting for the density of frequencies the curve are evaluated for - or conversely, if it would update this when I zoom in so that the curve always appears smooth, that would probably be even better. 

Thanks!

**Comment by chipmuenk** [comment]
You are right, this well-hidden feature ;-) exists: Go to Info -> Settings -> N_FFT and increase the number of points. Being the only setting with an unobvious label makes it even harder to find. Please try whether this works for you.

**Comment by stellarpower** [comment]
Ah, perfect! "It' not a bug, it's a feature". Perhaps could that go into the settings cog in the plot widget? Especially as it's a singleton all alone.

Cheers

**Comment by chipmuenk** [comment]
Hm, sounds like a good idea, however, the cog just calls a matplotlib routine that I don't know how to modify. I'll try to think of something but I'm closing the issue for now.

**Comment by stellarpower** [comment]
I guess keeping it in dedicated settings would still be sensible. However, it's mainly that it was a bit difficult to find. Easy once you know, but, I'd looked a few times for some global application settings or similar and just not scanned that button.
