### ISSUE TITLE
Make status window resizable

### ISSUE THREAD

**Issue by sp1nelson** [chipmuenk/pyFDA#77]
Shrink the status window to a smaller size and place it under the plot widget tab.

**Comment by chipmuenk** [comment]
PR #79 has implemented this successfully. Currently, the window can be either hidden or shown with a height of 4 lines which is fine for most situations. 

However, sometimes it would be nice to see more lines. Is it possible to make the window resizable?

**Comment by chipmuenk** [comment]
fixed by PR #102.
