### ISSUE TITLE
Please add tooltips to all user-selectable widgets

### ISSUE THREAD

**Issue by yurivict** [chipmuenk/pyFDA#81]
Particularly, if somebody isn't already an expert, they will be wondering what Fxx and Axx are.

**Comment by chipmuenk** [comment]
Excellent idea, I overlooked those as well!

**Comment by sp1nelson** [comment]
I am working on this while fixing other elliptical zero phase issues

**Comment by chipmuenk** [comment]
Nearly finished except for the firwin class.

**Comment by chipmuenk** [comment]
moving the remaining issue to #94
