### ISSUE TITLE
Designing IIR filters with N > 30 produce errors and sometimes even crash

### ISSUE THREAD

**Issue by yurivict** [chipmuenk/pyFDA#82]
Certain choices caused these errors:

```
[  ERROR] [pyfda.pyfda_lib:1147] could not broadcast input array from shape (0) into shape (2)
[  ERROR] [pyfda.filter_factory:216] Err. Code 18:

Error calling method 'BPman' of class 'Butter':
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
[WARNING] [pyfda.input_widgets.filter_specs:286] start_design_filt:
Attribute not found.
Unknown design method.
```

But it is hard to tell what's wrong from messages.

Screen looks like this:

![pyfda-errs1](https://user-images.githubusercontent.com/271906/30627037-a65a9718-9d82-11e7-8388-09e15ec79ea1.png)

**Comment by chipmuenk** [comment]
Could be anything ... which python and pyQt versions are you using? I fear I have introced some regression faults with py2 ...

**Comment by chipmuenk** [comment]
Hm, I've just noticed that you've set the order to N = 100 which is quite high for an IIR filter. When I set N = 100 pyfda crashes on my machine after showing the same errors you have. For orders N > 30 things start to go wrong (for other filter design methods as well). I should either limit the order or (better) check for warnings / errors coming back from the design routine.

**Comment by yurivict** [comment]
> Hm, I've just noticed that you've set the order to N = 100

Tried to push it to the extreme -)

> When I set N = 100 pyfda crashes on my machine after showing the same errors you have.

I also saw crashes.

> I should either limit the order

Hm, but all orders should work, IMO.

**Comment by chipmuenk** [comment]
IIR filters above a certain order always become instable ("certain" depending on the available numerical accuracy) - I've already used SOS (second-order sections) arithmetics where available. Direct form IIR filters tend to become instable above N = 10. That means even with SOS it becomes more and more difficult with increasing order to get a stable hardware or software implementation (yes, also with double float arithmetics).

**Comment by yurivict** [comment]
Ok!

**Comment by sp1nelson** [comment]
I have some fixes to catch some obvious errors with specifying bad order N values.  Also to test the simple IIR coefficients in a similar manner as scipy to notify the user before the scipy call fails.

**Comment by chipmuenk** [comment]
I've fixed an error in the error handling routine, crashes should no longer happen now. However, the following IIR filter designs still fail for high orders without error message:
[ ] chebychev 2
[ ] elliptic

**Comment by chipmuenk** [comment]
fixed in release 0.1

**Comment by yurivict** [comment]
@chipmuenk  Maybe you can consider making another RC or a release?
Because you've labeled some of my bugs as fixed, but I can only use released versions for the FreeBSD port that I am trying to create.

**Comment by chipmuenk** [comment]
Hm, the release 0.1 should fix most bugs - which bugs do you still see? However, if you want to design IIR filters with really high orders, the numerics underneath the corresponding scipy modules are not precise enough. Which leaves the question: What would you want to do with filter designs like that?
